// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

import petstoreVersions from './articles/docs/petstore_versioned/versions.json'

import { versionCrumb, versionSelector } from 'docusaurus-plugin-openapi-docs/lib/sidebars/utils'

import petstoreVersionedSidebar from './articles/docs/petstore_versioned/sidebar'
import petstoreVersionSidebar from './articles/docs/petstore_versioned/1.0.0/sidebar'

const sidebars = {
  'tutorialSidebar': [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],

  // single versioned sidebar
  // 'openApiSidebar': [
  //   {
  //     type: 'category',
  //     label: 'Petstore',
  //     link: {
  //       type: 'generated-index',
  //       title: 'Petstore API',
  //       description:
  //         'This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.',
  //       slug: '/category/petstore-api'
  //     },
  //     items: petstoreVersionedSidebar
  //   }
  // ],

  // multi versioned sidebar
  'petstore-2.0.0': [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: 'version-button'
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v2.0.0`)
    },
    {
      type: 'category',
      label: 'Petstore',
      link: {
        type: 'generated-index',
        title: 'Petstore API (latest)',
        description:
          'This is a sample server Petstore server. Generated by @docusaurus-plugin-openapi-docs plugin. Read more: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs',
        slug: '/category/petstore-versioned-api'
      },
      items: petstoreVersionedSidebar
    }
  ],

  'petstore-1.0.0': [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: 'version-button'
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`)
    },
    {
      type: 'category',
      label: 'Petstore',
      link: {
        type: 'generated-index',
        title: 'Petstore API (v1.0.0)',
        description:
          'This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.',
        slug: '/category/petstore-api-1.0.0'
      },
      items: petstoreVersionSidebar
    }
  ]
}

export default sidebars
